Traceback (most recent call last):
  File "/Users/robertwexler/miniconda3/envs/chem-402-5020/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/robertwexler/miniconda3/envs/chem-402-5020/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/robertwexler/miniconda3/envs/chem-402-5020/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/robertwexler/miniconda3/envs/chem-402-5020/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/robertwexler/miniconda3/envs/chem-402-5020/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/robertwexler/miniconda3/envs/chem-402-5020/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/robertwexler/miniconda3/envs/chem-402-5020/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

df = pd.read_csv("../_static/chapter-02/section-06/dulong_petit.csv")
df = df[df.Source == "use"].copy()
df["Atomic Number"] = df["Atomic Number"].astype(int)
df["Molar (J/molÂ·K)"] = df["Molar (J/molÂ·K)"].astype(float)
df["Molar (R)"] = df["Molar (J/molÂ·K)"] / 8.314

# Remove elemental gases
elemental_gases = ["H", "He", "N", "O", "F", "Ne", "Cl", "Ar", "Kr", "Xe", "Rn"]
df = df[~df.Element.isin(elemental_gases)]
print(df)

fig, axs = plt.subplot_mosaic([[0]], figsize=(4, 4))

# axs[0].scatter(df["Atomic Number"], df["Molar (R)"], color="black")
# axs[0].set_xlabel("Atomic Number")
# axs[0].set_ylabel("Heat Capacity (R)")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/n9/q030dl3x6qgfqffys4wc7d4c0000gn/T/ipykernel_11689/2887359502.py[0m in [0;36m?[0;34m()[0m
[1;32m      7[0m [0mdf[0m[0;34m[[0m[0;34m"Molar (R)"[0m[0;34m][0m [0;34m=[0m [0mdf[0m[0;34m[[0m[0;34m"Molar (J/molÂ·K)"[0m[0;34m][0m [0;34m/[0m [0;36m8.314[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0;31m# Remove elemental gases[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0melemental_gases[0m [0;34m=[0m [0;34m[[0m[0;34m"H"[0m[0;34m,[0m [0;34m"He"[0m[0;34m,[0m [0;34m"N"[0m[0;34m,[0m [0;34m"O"[0m[0;34m,[0m [0;34m"F"[0m[0;34m,[0m [0;34m"Ne"[0m[0;34m,[0m [0;34m"Cl"[0m[0;34m,[0m [0;34m"Ar"[0m[0;34m,[0m [0;34m"Kr"[0m[0;34m,[0m [0;34m"Xe"[0m[0;34m,[0m [0;34m"Rn"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 11[0;31m [0mdf[0m [0;34m=[0m [0mdf[0m[0;34m[[0m[0;34m~[0m[0mdf[0m[0;34m.[0m[0mElement[0m[0;34m.[0m[0misin[0m[0;34m([0m[0melemental_gases[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     12[0m [0mprint[0m[0;34m([0m[0mdf[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0;34m[0m[0m
[1;32m     14[0m [0mfig[0m[0;34m,[0m [0maxs[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0msubplot_mosaic[0m[0;34m([0m[0;34m[[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m][0m[0;34m,[0m [0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m4[0m[0;34m,[0m [0;36m4[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.local/lib/python3.10/site-packages/pandas/core/generic.py[0m in [0;36m?[0;34m(self, name)[0m
[1;32m   5985[0m             [0;32mand[0m [0mname[0m [0;32mnot[0m [0;32min[0m [0mself[0m[0;34m.[0m[0m_accessors[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5986[0m             [0;32mand[0m [0mself[0m[0;34m.[0m[0m_info_axis[0m[0;34m.[0m[0m_can_hold_identifiers_and_holds_name[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5987[0m         ):
[1;32m   5988[0m             [0;32mreturn[0m [0mself[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5989[0;31m         [0;32mreturn[0m [0mobject[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: 'DataFrame' object has no attribute 'Element'

